// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKIbec58ttZ9hcyKEZyPcoCRim1oaDh_I',
    appId: '1:219805973846:web:0c367b0f20ba7a80252af7',
    messagingSenderId: '219805973846',
    projectId: 'wechat-69ab8',
    authDomain: 'wechat-69ab8.firebaseapp.com',
    storageBucket: 'wechat-69ab8.firebasestorage.app',
    measurementId: 'G-V2ZDR6FV6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5kWx5V4tJESTJ1fUTP_QXRQGKuN_oMuk',
    appId: '1:219805973846:android:a806863a3b33cbf7252af7',
    messagingSenderId: '219805973846',
    projectId: 'wechat-69ab8',
    storageBucket: 'wechat-69ab8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_QHwuiN7x32Zwm096E8MKlBMlx8WXOXQ',
    appId: '1:219805973846:ios:5604eb9b7e918864252af7',
    messagingSenderId: '219805973846',
    projectId: 'wechat-69ab8',
    storageBucket: 'wechat-69ab8.firebasestorage.app',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_QHwuiN7x32Zwm096E8MKlBMlx8WXOXQ',
    appId: '1:219805973846:ios:5604eb9b7e918864252af7',
    messagingSenderId: '219805973846',
    projectId: 'wechat-69ab8',
    storageBucket: 'wechat-69ab8.firebasestorage.app',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKIbec58ttZ9hcyKEZyPcoCRim1oaDh_I',
    appId: '1:219805973846:web:7bfcde6241138ef2252af7',
    messagingSenderId: '219805973846',
    projectId: 'wechat-69ab8',
    authDomain: 'wechat-69ab8.firebaseapp.com',
    storageBucket: 'wechat-69ab8.firebasestorage.app',
    measurementId: 'G-1WLN9H3S95',
  );

}