// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZ5YY__wOHuBSYBOBFqSPKD5kLMgqerM',
    appId: '1:601218547398:web:d6974c57398d2cd14761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    authDomain: 'wechat3008-634cd.firebaseapp.com',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
    measurementId: 'G-F3JFGE9MMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDByzXA7PlGTZHnmMHPV1PTzyjpIlCjNxk',
    appId: '1:601218547398:android:147beb9a53b7eb804761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85dSAPczS4PDx_yoed0lZ7LSIgqEmTzw',
    appId: '1:601218547398:ios:a2717613c829f94b4761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
    iosClientId: '601218547398-h60en446sj4mfculj79va2gf1pp798ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85dSAPczS4PDx_yoed0lZ7LSIgqEmTzw',
    appId: '1:601218547398:ios:a2717613c829f94b4761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
    iosClientId: '601218547398-h60en446sj4mfculj79va2gf1pp798ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZ5YY__wOHuBSYBOBFqSPKD5kLMgqerM',
    appId: '1:601218547398:web:27e80939b972aa7c4761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    authDomain: 'wechat3008-634cd.firebaseapp.com',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
    measurementId: 'G-N5S1VRNZ8Z',
  );
}
